version: 1.1.0
# your avatar url
avatar: /img/avatar.jpg
favicon: /img/avatar.jpg

#If the blog placement location is not the root directory, you can solve the static file path error problem by configuring this path.
# For example, if the access address is ntxinh.github.io/blog, it needs to be configured as blog_path: /blog for normal access.
blog_path: /blogs

#The link icons are displayed in the same order as below
link:
  theme: color # Link style, color: color icon white: black and white icon
  items:
    rss: # /atom.xml
    github: https://github.com/ntxinh
    facebook:
    twitter: https://twitter.com/nguyentrucxinh
    linkedin: https://linkedin.com/in/ntxinh
    instagram:
    reddit:
    weibo:
    jianshu:
    zhihu:
    csdn:
    oschina:
    juejin:
    email: ntxinh@outlook.com
    qq:
    kugou:
    neteasemusic:

##########multi-author mode############
author:
  on: false
  authors:
    author1: ntxinh
    author2:
##############################

# Article classification settings
category:
  num: true # Display the number of articles by category
  sub: true # Enable multi-level classification
  sort:
    - Read
    - Tool
    - Big front-end
    - Rear end
    - Database
    - Operation and maintenance
  width:
    lg: 120 # 1468px<Screen width Left category width
    md: 100 # 1024px<Screen width <=1468px Left category width
    sm: 100 # 426px<Screen width <=1024px left category width (ipad)
# Multi-level classification description:
# For example, if you set multiple menus in an article, the default is a multi-level menu, that is: Tools>hexo
# categories:
#   - Tool
#   - hexo

# Shortcut key
shortcutKey: true

# Custom menu in the lower left corner
menu:
  about:  # 'About' button
    on: true # Whether to display
    url: https://ntxinh.github.io #/about  # Jump link
    type: 3 # Jump type 1: Asynchronous jump within the site 2: Jump to the current page 3: Open a new tab page
  friend: # 'Friend link' button
    on: false # Whether to display
  menus: # The other added menus are written under menus, as follows: dynamic menu 1, dynamic menu 2, dynamic menu 3
    相册: # photo album
      on: false
      url: /photo
      type: 1  # Jump type 1: Asynchronous jump within the site
    叶落阁: # Ye Luo Pavilion
      on: false
      url: https://ntxinh.github.io/
      type: 2  # Jump type 2: Jump to the current page
    github:
      on: false
      url: https://github.com/ntxinh
      type: 3  # Jump type 3: Open a new tab page

# Statement at the end of the article
article_txt: Please indicate the source when reprinting. You are welcome to verify the sources cited in the article, and you are welcome to point out any errors or unclear expressions. You can comment in the comment area below or email to ntxinh@outlook.com

bottom_text: ©2023-Present ntxinh's blog
# Customize the site copyright information at the bottom of the page
# If left blank, it will be customized as ©2017 author (this author is configured in hexo root directory _config.yml)

# Bottom registration number
miit:
  on: false
  info: Beijing ICP Certificate No. 030173
  url: http://beian.miit.gov.cn/ # The default link is http://beian.miit.gov.cn/


reward: true
# true Turn on reward function

searchAll: false
# true Enable full text search
# Turning on this feature requires the following operations:
# 1. Execute npm install hexo-generator-search --save in the hexo root directory to install the plug-in
# 2. Add the following content to _config.xml in the hexo root directory
# search:
#   path: search.xml
#   field: post


copyright: false
# Copyright info. of post | Copyright information at the end of the article

word_count: false
# true turns on word count
# To enable this function, you need to install a plug-in: execute npm i hexo-wordcount --save in the hexo root directory


# No website count setting
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit: true
  page_visit: true

##########Custom style settings##############
# Table of contents | Article directory
toc:
  max_depth: 3  # 1 - 6 (h1-h6) The maximum number of directory levels

#Article list The style when the mouse is moved up. If it is empty, the default effect will be used.
article_list:
  title: '#383636' # Article list title color
  datetime: '#5e5e5f' # Article publication date color
  hover:
    background: '#e2e0e0'  # Background color: Several types are provided: '#c1bfc1' '#fbf4a8'
    color:     # There are several text colors available: '#ffffff'
# Note: If the color contains #, use single quotes '

# Article list background image
article_bg_img:
  on: false # Whether to turn on
  src: https://i.loli.net/2019/07/22/5d3521411f3f169375.png
  opacity: 0.3 # Background image transparency, range 0 ～ 1

# list style
list: normal
# normal : normal style
# thread: There is a wireframe in the outer circle of the list

#Quote block style
blockquote: github
# github: similar to github reference fast
# bracket: similar to the style of two left and right braces

# table style
table: green_title
# When empty, it is similar to github’s table style
# green green style
# green_title table style with cyan header

# Home page background image
index_bg_img:
# Other page background images
other_bg_img:

# Click on the image to enlarge the style
img_resize: default
# Optional values:
# default: Default (simple amplification written by myself)
# photoSwipe: Use photoSwipe plugin

# Code segment highlighting style, markdown syntax `demo`
code:
  theme: dark-red
#Supported themes:
# dark-red: red (default)
# github: github style (gray background, black text)

highlight:
  on: true # true turns on code highlighting. To turn it on, you need to turn off the highlight in the blog _config.yml.
  lineNum: false # true displays line number
  copy: true # copy function
  theme: atom-light
# Code highlighting theme, the effect can be viewed at https://highlightjs.org/static/demo/
#Supported themes:
# sublime: Refer to sublime’s highlight theme
#darcula: Refer to the darcula theme in idea
# atom-dark: Reference to Atom’s dark theme
# atom-light: Reference to Atom’s light theme
# github : Refer to the GitHub version of the highlighted theme
# github-gist : GitHub-Gist theme
#brown-paper : Kraft paper effect
# gruvbox-light : light theme for gruvbox
#gruvbox-dark: dark theme for gruvbox
#rainbow :
# railscasts :
#sunburst :
#kimbie-dark :
#kimbie-light :
#school-book : paper effect
#zenbum : oschina also choose this highlighted theme

# MathJax mathematical formula support
mathjax:
  on: true #Whether to enable
  per_page: false # If only a single page is rendered, set this option to false and add mathjax: true to the page.

# Mermaid support
mermaid:
  on: false
  cdn: //cdn.jsdelivr.net/npm/mermaid@8.4.2/dist/mermaid.min.js
  #cdn: //cdnjs.cloudflare.com/ajax/libs/mermaid/8.3.1/mermaid.min.js
  options: # For more configuration information, please refer to https://mermaidjs.github.io/#/mermaidAPI
    theme: 'default'
    startOnLoad: true
    flowchart:
      useMaxWidth: false
      htmlLabels: true

##############################

# Links
friends:
  叶落阁: https://ntxinh.github.io/

##########Comment settings#############
comment:
  on: false
  type: gitalk  # Comment system: gitalk, disqus, gitment, utteranc, livere, note: when using, configure it in the corresponding location below
  comment_count: true # Display the number of comments below the article title. Currently only supports gitalk and disqus.
  ## Instructions for use https://yelog.org//2020/05/23/3-hexo-comment/
# Configuration of each comment system ↓↓

disqus:
  shortname:
  # disqus comment system was certified by GFW in September 2016 and cannot be used in mainland China.
  # Get shortname: https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-


gitalk:
  githubID: ntxinh
  repo: ntxinh.github.io
  ClientID:
  ClientSecret:
  adminUser: ntxinh
  distractionFreeMode: true
  language: en
  perPage: 10
#gitalk: A third-party chat plug-in made using github issue
# https://github.com/gitalk/gitalk
# Parameter introduction:
#githubID: github username
# repo: Which repository to use for the issue
# ClientID and ClientSecret will be generated when creating OAuth application: https://github.com/settings/applications/new
# adminUser: must be a collaborator (with write permission) of the above warehouse, just use your own github username
#distractionFreeMode: full screen mask effect
# language: Language: Support: en / zh-CN / zh-TW three types
# perPage: Data size loaded each time, default 10, maximum 100


gitment:
  owner: ntxinh
  repo: ntxinh.github.io
  client_id:
  client_secret:
  # gitment: Comment system implemented through github issue
  # Open source address: https://github.com/imsun/gitment
  # Instructions for use :

livere:
  data_uid:
  # Livere: http://livere.com/
  # Instructions for use: https://yelog.org//2020/05/23/3-hexo-comment/

utteranc:
  repo: xxx/xxx.github.io # The warehouse that hosts comments, fill in your newly created warehouse
  issue_term: pathname # Mapping relationship between Issue and blog post
  label: utteranc # Label added to the created Issue
  theme: github-light # Theme, please check the official documentation for optional themes https://utteranc.es/#heading-theme
#Official documentation https://utteranc.es/
# Instructions for use https://yelog.org//2020/05/23/3-hexo-comment/

##############################

##########CDN settings#############
CDN:
  jquery: //cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  jquery_cookie: //cdn.jsdelivr.net/npm/jquery.cookie@1.4.1/jquery.cookie.min.js
  highlight: //cdn.jsdelivr.net/npm/highlightjs@9.16.2/highlight.pack.min.js
  pjax: //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
  animate: //cdn.jsdelivr.net/npm/animate.css@4.1.0/animate.min.css
  nprogres_js: //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
  mathjax: //cdn.jsdelivr.net/npm/mathjax@2.7.8/unpacked/MathJax.js?config=TeX-MML-AM_CHTML
  photoswipe_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.js
  photoswipe_ui_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js
  photoswipe_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.css
  photoswipe_skin_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.min.css
##############################
